### ISSUE TITLE
`test_count` will always be 3. It's not total but a constant. 

### ISSUE THREAD

**Issue by raikrahul** [Seagate/cortx-utils#187]
https://github.com/Seagate/cortx-utils/blob/f5f02cb67913feaf077742dc945ba87de34f35ee/c-utils/src/test/management/md5hash_test.c#L129

We do not publish which tests fail.

This makes the objective of a test case suite not useful.

Please make sure the code is readable, usable, modular; for the average github user.

```
printf("Total tests  = %d\n", test_count);

rc = test_basic_string();
	if (rc) {
		test_failed++;
                printf("\nbasic string test fails!");

	}

	rc = test_empty_string();
	if (rc) {
		test_failed++;
                printf("\nempty  string test fails!");

	}

	rc = test_numeral_string();
	if (rc) {
		test_failed++;
                printf("\nnumeric string test fails!");

	}
	/* Test summary */
	
	printf("Tests passed = %d\n", test_count-test_failed);
	printf("Tests failed = %d\n", test_failed);
```

**Comment by hessio** [comment]
Hi @raikrahul ! Thanks you so much for participating in our community. If you read our contributing guidelines, we aim to create a respectful and inclusive community for everyone. Part of this is ensuring that criticism is always constructive, helpful, and doesn't shame or attack others. Since this is an open source project, it is always in development and there is always room for improvement. We welcome suggested changes, but please keep the contributing guidelines in mind moving forward. Thank you!
