### ISSUE TITLE
Indentation is not inclined 

### ISSUE THREAD

**Issue by raikrahul** [Seagate/cortx-utils#188]
https://github.com/Seagate/cortx-utils/blob/f5f02cb67913feaf077742dc945ba87de34f35ee/c-utils/src/cortx/m0store.c#L243

I see in all but one function, `int rc` being   initialized?

Is there something special about that function? 

For the average github user, it's impossible to infer it. I see in rest of the code base, `int rc` as seldom initialized.

**Comment by hessio** [comment]
Hi @raikrahul ! Thanks you so much for participating in our community. If you read our contributing guidelines, we aim to create a respectful and inclusive community for everyone. Part of this is ensuring that criticism is always constructive, helpful, and doesn't shame or attack others. Since this is an open source project, it is always in development and there is always room for improvement. We welcome suggested changes, but please keep the contributing guidelines in mind moving forward. Thank you!
