### ISSUE TITLE
Some of the functions in the file are commented, others aren't. Some have blank comments?

### ISSUE THREAD

**Issue by raikrahul** [Seagate/cortx-utils#192]
https://github.com/Seagate/cortx-utils/blob/f5f02cb67913feaf077742dc945ba87de34f35ee/c-utils/src/cortx/m0store.c#L314

I will be happy to read the `.c` file guidelines if any.

Please keep the avereage github reader in mind and the github community in mind, before uploading.

**Comment by hessio** [comment]
Hi @raikrahul ! Thanks you so much for participating in our community. If you read our contributing guidelines, we aim to create a respectful and inclusive community for everyone. Part of this is ensuring that criticism is always constructive, helpful, and doesn't shame or attack others. Since this is an open source project, it is always in development and there is always room for improvement. We welcome suggested changes, but please keep the contributing guidelines in mind moving forward. Thank you!

**Comment by johnbent** [comment]
As always, thanks for the feedback @raikrahul and for participating in our community.
