### ISSUE TITLE
Is that the correct usage

### ISSUE THREAD

**Issue by raikrahul** [Seagate/cortx-utils#193]
https://github.com/Seagate/cortx-utils/blob/f5f02cb67913feaf077742dc945ba87de34f35ee/c-utils/src/cortx/m0common.h#L56

**Comment by hessio** [comment]
Hi @raikrahul ! Thanks you so much for participating in our community. If you read our contributing guidelines, we aim to create a respectful and inclusive community for everyone. Part of this is ensuring that criticism is always constructive, helpful, and doesn't shame or attack others. Since this is an open source project, it is always in development and there is always room for improvement. We welcome suggested changes, but please keep the contributing guidelines in mind moving forward. Thank you!

**Comment by johnbent** [comment]
As always, thanks for the feedback @raikrahul and for participating in our community.
