### ISSUE TITLE
py-utils/Readme.md error : build section

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-utils#634]
Hi, 

For README.md ( in **cortx-utils/py-utils/README.md** ), **Build** section:
```
cd ..
./jenkins/build.sh -v 2.0.0 -b 2
```

seem like should be 
```
cd cortx-utils
./jenkins/build.sh -v 2.0.0 -b 2
```

Cause it should work following git command 

`git clone --recursive https://github.com/Seagate/cortx-utils -b main`

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-26848. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by justinzw** [comment]
I submitted a pull request to solve the issue

**Comment by rahul-tripathi-git** [comment]
This issue is already fixed in main branch: https://github.com/Seagate/cortx-utils/tree/main/py-utils#build
Closing this issue.

**Comment by cortx-admin** [comment]
> Rahul Tripathi commented in Jira Server:

Already fixed in main branch

**Comment by cortx-admin** [comment]
> Rahul Tripathi commented in Jira Server:

This issue is already fixed in main branch.

**Comment by cortx-admin** [comment]
> Rahul Tripathi commented in Jira Server:

Closing.
